<template>
  <div class="ais">
    <header class="ais__head">
      <div>
        <span class="ais__eyebrow">Post-call summary · {{ summary.id }}</span>
        <h3 class="ais__title">{{ summary.peer }} · {{ summary.duration }} · {{ summary.date }}</h3>
      </div>
      <span class="ais__score" :class="`ais__score--${sentimentTone(summary.sentiment)}`">
        sentiment {{ summary.sentiment > 0 ? '+' : '' }}{{ summary.sentiment.toFixed(2) }}
      </span>
    </header>

    <section class="ais__tldr">
      <h4 class="ais__h4">TL;DR</h4>
      <p>{{ summary.tldr }}</p>
    </section>

    <section class="ais__grid">
      <article class="ais__card">
        <h4 class="ais__h4">Topics</h4>
        <ul class="ais__chips" role="list">
          <li v-for="t in summary.topics" :key="t.label" class="ais__chip">
            <span class="ais__chip-label">{{ t.label }}</span>
            <span class="ais__chip-count">{{ t.mentions }}×</span>
          </li>
        </ul>
      </article>

      <article class="ais__card">
        <h4 class="ais__h4">Action items</h4>
        <ul class="ais__actions" role="list">
          <li v-for="a in summary.actions" :key="a.id" class="ais__action" :class="`ais__action--${a.priority}`">
            <label class="ais__action-check">
              <input type="checkbox" :checked="a.done" @change="toggle(a.id)" />
              <span>{{ a.text }}</span>
            </label>
            <span class="ais__action-meta">
              <span class="ais__action-prio">{{ a.priority }}</span>
              <span v-if="a.owner">→ {{ a.owner }}</span>
              <span v-if="a.due">· due {{ a.due }}</span>
            </span>
          </li>
        </ul>
      </article>
    </section>

    <section class="ais__transcript" aria-label="Transcript excerpt">
      <h4 class="ais__h4">Transcript (first minute)</h4>
      <ol class="ais__lines" role="list">
        <li v-for="l in summary.transcript" :key="l.id" class="ais__line" :class="`ais__line--${l.who}`">
          <span class="ais__line-time">{{ l.t }}</span>
          <span class="ais__line-who">{{ l.who === 'agent' ? 'AGENT' : 'CALLER' }}</span>
          <span class="ais__line-text">{{ l.text }}</span>
        </li>
      </ol>
    </section>

    <footer class="ais__foot">
      <span>Summary generated by GPT-4o from diarised transcript · 1,842 tokens · {{ summary.latency }}</span>
      <span class="ais__grade">Human review: <strong>not required</strong> (confidence 0.94)</span>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { reactive } from 'vue'

const summary = reactive({
  id: 'c-50217',
  peer: 'Maya Chen · ACME Corp',
  duration: '08:42',
  date: '2026-04-20 11:14',
  sentiment: -0.32,
  latency: '1.8 s',
  tldr: 'Customer reported a failed webhook delivery from last Thursday. Root cause was an expired API key rotated without notifying their integration team. Agent re-issued key, verified delivery of a test payload, and committed to adding integration-owner contacts to the key-rotation notification list.',
  topics: [
    { label: 'webhook delivery', mentions: 14 },
    { label: 'API key rotation', mentions: 9 },
    { label: 'notifications', mentions: 6 },
    { label: 'SLA credit', mentions: 2 },
  ],
  actions: [
    { id: 'a1', text: 'Add integrations@acmecorp.com to key-rotation notify list', priority: 'high', owner: 'Jordan', due: '2026-04-22', done: false },
    { id: 'a2', text: 'File post-mortem on silent rotation policy', priority: 'medium', owner: 'Platform', due: '2026-04-27', done: false },
    { id: 'a3', text: 'Apply 1-day SLA credit (ticket #T-90441)', priority: 'high', owner: 'Billing', due: '2026-04-21', done: true },
    { id: 'a4', text: 'Follow-up email with test payload example', priority: 'low', owner: 'Jordan', due: null, done: true },
  ] as { id: string; text: string; priority: 'high' | 'medium' | 'low'; owner: string | null; due: string | null; done: boolean }[],
  transcript: [
    { id: 't1', t: '00:03', who: 'agent',  text: 'ACME support, this is Jordan — what\'s going on?' },
    { id: 't2', t: '00:06', who: 'caller', text: 'Our webhooks stopped firing last Thursday. We didn\'t get any error response.' },
    { id: 't3', t: '00:14', who: 'agent',  text: 'Let me pull your account. You\'re on plan team, webhook endpoint is https://hooks.acmecorp.com/inbound?' },
    { id: 't4', t: '00:22', who: 'caller', text: 'Correct. We monitor it with Grafana and it went silent around 14:30 UTC on the 16th.' },
    { id: 't5', t: '00:31', who: 'agent',  text: 'I see it now — the signing key on that endpoint was rotated at 14:27 UTC. Were you notified?' },
    { id: 't6', t: '00:40', who: 'caller', text: 'No, that\'s the problem. The email went to our old billing contact who left in January.' },
  ],
})

const toggle = (id: string) => {
  const a = summary.actions.find(x => x.id === id)
  if (a) a.done = !a.done
}

const sentimentTone = (v: number) => v > 0.15 ? 'ok' : v < -0.15 ? 'warn' : 'neutral'
</script>

<style scoped>
.ais {
  --ink: var(--demo-ink, #1a1410);
  --paper: var(--demo-paper, #faf6ef);
  --paper-deep: var(--demo-paper-deep, #f2eadb);
  --rule: var(--demo-rule, #d9cfbb);
  --accent: var(--demo-accent, #c2410c);
  --muted: var(--demo-muted, #6b5d4a);
  --mono: var(--demo-mono, 'JetBrains Mono', ui-monospace, monospace);
  --sans: var(--demo-sans, 'IBM Plex Sans', system-ui, sans-serif);

  display: flex; flex-direction: column; gap: 0.85rem;
  color: var(--ink); font-family: var(--sans);
}

.ais__head { display: flex; justify-content: space-between; align-items: flex-end; gap: 0.5rem; flex-wrap: wrap; }
.ais__eyebrow {
  font-family: var(--mono); font-size: 0.64rem; font-weight: 700;
  letter-spacing: 0.16em; text-transform: uppercase; color: var(--muted);
}
.ais__title { margin: 0.1rem 0 0; font-size: 1rem; font-weight: 600; font-variant-numeric: tabular-nums; }
.ais__score {
  font-family: var(--mono); font-size: 0.7rem; font-weight: 700;
  padding: 0.25rem 0.55rem; border-radius: 2px;
  background: var(--paper-deep); border: 1px solid var(--rule); color: var(--muted);
  font-variant-numeric: tabular-nums;
}
.ais__score--ok { color: #15803d; border-color: #15803d; }
.ais__score--warn { color: #b91c1c; border-color: #b91c1c; }

.ais__h4 {
  margin: 0 0 0.45rem;
  font-family: var(--mono); font-size: 0.64rem; font-weight: 700;
  letter-spacing: 0.16em; text-transform: uppercase; color: var(--muted);
}

.ais__tldr {
  background: var(--paper); border: 1px solid var(--rule); border-radius: 2px;
  padding: 0.65rem 0.85rem;
}
.ais__tldr p { margin: 0; font-size: 0.88rem; line-height: 1.5; }

.ais__grid {
  display: grid; gap: 0.5rem;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
}
.ais__card {
  background: var(--paper); border: 1px solid var(--rule); border-radius: 2px;
  padding: 0.65rem 0.85rem;
}

.ais__chips { list-style: none; padding: 0; margin: 0; display: flex; gap: 0.3rem; flex-wrap: wrap; }
.ais__chip {
  display: flex; align-items: center; gap: 0.35rem;
  padding: 0.25rem 0.55rem;
  background: var(--paper-deep); border: 1px solid var(--rule); border-radius: 2px;
}
.ais__chip-label { font-size: 0.78rem; }
.ais__chip-count { font-family: var(--mono); font-size: 0.66rem; color: var(--accent); font-weight: 700; }

.ais__actions { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.35rem; }
.ais__action {
  padding: 0.4rem 0.55rem;
  background: var(--paper-deep); border: 1px solid var(--rule); border-left-width: 3px; border-radius: 2px;
  display: flex; flex-direction: column; gap: 0.2rem;
}
.ais__action--high { border-left-color: var(--accent); }
.ais__action--medium { border-left-color: var(--muted); }
.ais__action--low { border-left-color: var(--rule); }
.ais__action-check { display: flex; gap: 0.45rem; align-items: baseline; cursor: pointer; }
.ais__action-check input { margin-top: 0.15rem; accent-color: var(--accent); }
.ais__action-check span { font-size: 0.84rem; }
.ais__action-check input:checked + span { text-decoration: line-through; color: var(--muted); }
.ais__action-meta {
  display: flex; gap: 0.35rem; flex-wrap: wrap;
  font-family: var(--mono); font-size: 0.64rem; color: var(--muted);
  padding-left: 1.35rem;
}
.ais__action-prio { font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: var(--accent); }
.ais__action--low .ais__action-prio { color: var(--muted); }

.ais__transcript {
  background: var(--paper); border: 1px solid var(--rule); border-radius: 2px;
  padding: 0.65rem 0.85rem;
}
.ais__lines { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.25rem; }
.ais__line {
  display: grid; grid-template-columns: 3.3rem 4rem 1fr; gap: 0.5rem; align-items: baseline;
  padding: 0.25rem 0.45rem;
  background: var(--paper-deep); border-radius: 2px;
  font-family: var(--mono); font-size: 0.74rem;
}
.ais__line--agent { border-left: 3px solid var(--accent); }
.ais__line--caller { border-left: 3px solid var(--muted); }
.ais__line-time { color: var(--muted); font-variant-numeric: tabular-nums; }
.ais__line-who { font-size: 0.6rem; font-weight: 700; letter-spacing: 0.14em; color: var(--muted); }
.ais__line--agent .ais__line-who { color: var(--accent); }
.ais__line-text { color: var(--ink); line-height: 1.4; }

.ais__foot {
  display: flex; gap: 0.5rem; justify-content: space-between; flex-wrap: wrap;
  padding: 0.55rem 0.75rem;
  background: var(--paper-deep); border: 1px solid var(--rule); border-radius: 2px;
  font-family: var(--mono); font-size: 0.68rem; color: var(--muted);
}
.ais__grade strong { color: #15803d; }
</style>
