[general]

[sandbox_bridge]
type=bridge
max_members=10
mixing_interval=20
internal_sample_rate=auto
record_conference=no

[sandbox_user]
type=user
announce_user_count=yes
announce_user_count_all=2
announce_only_user=yes
music_on_hold_when_empty=yes
quiet=no
dsp_drop_silence=yes
dsp_talking_threshold=160
dsp_silence_threshold=2500
talk_detection_events=yes
