[general]
format=wav49|gsm|wav
attach=no
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3

[sandbox]
demo1 => 1234,Demo 1,demo1@localhost,,attach=no
demo2 => 1234,Demo 2,demo2@localhost,,attach=no
demo3 => 1234,Demo 3,demo3@localhost,,attach=no
demo4 => 1234,Demo 4,demo4@localhost,,attach=no
demo5 => 1234,Demo 5,demo5@localhost,,attach=no
demo6 => 1234,Demo 6,demo6@localhost,,attach=no
